### ISSUE TITLE
Question about reproducing the results

### ISSUE THREAD

**Issue by JunkunPeng17** [gist-ailab/domain-specific-block-selection-and-paired-view-pseudo-labeling-for-online-TTA#1]
Hi, many thanks for making the codes available to the public. It is really a good job. I carefully followed your instructions to install the corresponding environment. Currently, I have tested 2 sets of experiments on CIFAR100-C based on ResNext-29A and WRN40-2A, respectively, but got a very high error rate. I think the problem may be with loading blocks. When I run the code directly, an error will be reported. According to the error, I indexed to test_time.py line 209.
![image](https://github.com/gist-ailab/domain-specific-block-selection-and-paired-view-pseudo-labeling-for-online-TTA/assets/56396894/52198fbe-2803-44ad-a6d2-70b01483aec9)

 The blocks are set to block1 by default, causing the param to be unable to set and report the error. Based on my understanding, the block list is set by selecting the specific type (model), so I commented out line 209, and then the program can run normally and set the block list of the corresponding model. But the error rates of the two results are 84.21 and 79.68, respectively, as shown in the log below.
![image](https://github.com/gist-ailab/domain-specific-block-selection-and-paired-view-pseudo-labeling-for-online-TTA/assets/56396894/34eb9a1a-3122-4b45-8d4e-56f9d8a03921)
![image](https://github.com/gist-ailab/domain-specific-block-selection-and-paired-view-pseudo-labeling-for-online-TTA/assets/56396894/5934aa71-0245-4d87-b700-61180d4b3854)

**Comment by JunkunPeng17** [comment]
Sorry to bother you. I've solved the problem by uncommenting the code at line 208. Otherwise, it is equivalent to the program selecting all blocks for TTA, and the reproduced results can basically achieve the performance reported in the paper. The image below is the result based on the WRN40-2A:
![image](https://github.com/gist-ailab/domain-specific-block-selection-and-paired-view-pseudo-labeling-for-online-TTA/assets/56396894/a492b44a-7d3e-4c03-a64d-57e7f73f476e)

**Comment by birdomi** [comment]
Thank you for your attention in our work.

I mistakenly upload code, which I used for initial setup (block selection is not used).

We correct the code that uses block selection appropriately.
