### ISSUE TITLE
About paired-view consistency

### ISSUE THREAD

**Issue by huamiao1012** [gist-ailab/domain-specific-block-selection-and-paired-view-pseudo-labeling-for-online-TTA#3]
Hello! I have some questions about the sentence: "This is based on insight that the high-level feature in the test image can be affected by domain shifts, and all parameters should be adjusted to increase adaptation performance." in Section 3.1. Why the domain-invariant block still affected by domain shifts ?

**Comment by birdomi** [comment]
Hello, thank you for your attention in our work.

We wrote the sentence "This is based on insight that the high-level feature in the test image can be affected by domain shifts, and all parameters should be adjusted to increase adaptation performance." based on two insights.

First, the image with significant domain shifts can have object with different shape and may need to adjust high-level blocks. For example, a blurred image can present objects with blurry shapes.

Second, in practice, the blocks do not solely involve in either domain-invariant feature extraction or domain-specific feature extraction. For example, the middle block can be involved in both domain-invariant and domain-specific feature extraction. 

Therefore, we believe that all blocks should be adjusted to further increase adaptation performance in the current test domain.

Hope this is helpful for your understanding.
